### ISSUE TITLE
블로그 내 댓글 등록이 불가능합니다 ㅠㅠ

### ISSUE THREAD

**Issue by kecan0406** [univdev/univdev.github.io#19]
좋은 글들 작성해주셔서 감사합니다!

댓글 등록 부분이 제대로 동작하지 않는 것 같아 이슈 남깁니다

**Comment by univdev** [comment]
부족한 글 읽어주시고 블로그 개설 후 첫 피드백 남겨주셔서 감사합니다!

댓글 작성에 불편함을 드려 죄송합니다 😢 
빠른 시일 내에 수정하도록 하겠습니다!

**Comment by univdev** [comment]
중요한 버그에 대한 제보 감사드립니다 :)
Github 레포지토리를 재개설한 뒤에 Discussions에 댓글이 달릴 수 있는 카테고리를 개설하지 않아 발생한 이슈였네요 ;(

수정 완료 되어 해당 이슈 닫겠습니다!
